const DEFAULT_DASHBOARD_DESTINATION_SLUG = "batam";
const DASHBOARD_FEATURED_LIMIT = 4;
const DASHBOARD_EXPLORE_MORE_LIMIT = 12;

module.exports = {
  DASHBOARD_EXPLORE_MORE_LIMIT,
  DASHBOARD_FEATURED_LIMIT,
  DEFAULT_DASHBOARD_DESTINATION_SLUG,
};
