const DASHBOARD_FEATURED_LIMIT = 4;
const DASHBOARD_FEATURED_POOL_LIMIT = 20;
const DASHBOARD_SEARCH_DEFAULT_LIMIT = 12;

module.exports = {
  DASHBOARD_FEATURED_LIMIT,
  DASHBOARD_FEATURED_POOL_LIMIT,
  DASHBOARD_SEARCH_DEFAULT_LIMIT,
};
